[package]
name = "seclab-host-scanner"
version = "0.1.0-alpha.1"
edition = "2024"

[dependencies]
seclab-suite-runtime-sdk = { git = "https://github.com/seclab-dev/seclab-suite-runtime-sdk.git", tag = "rust-0.1.0-alpha.1" }

axum = "0.8.9"
rust-embed = "8.11.0"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.52.3", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ipnet = "2.10.1"
futures-util = "0.3"
tower-http = { version = "0.6", features = ["cors"] }
mime_guess = "2.0"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
